# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI (main)

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    if: ${{ github.event.pull_request.merged }}
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: |
        npm version minor
        ls -a
        echo '[user]' >> .git/config
        echo '  name="lu"' >> .git/config
        echo '  email="10154508169@stu.ecnu.edu.cn"' >> .git/config
        cat .git/config
        git add package.json
        git commit -m "bump minor version."
        git push -u origin main

